name: Validate Build Number
on:
  pull_request:
    branches:
      - main

jobs:
  validate-build-number:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: "Ensure version or build number is updated"
        uses: brettcannon/check-for-changed-files@v1
        with:
          file-pattern: "app.config.js"
          failure-message: "Version # or Build # in ${file-pattern} needs to be updated."
